"""Initial migration

Revision ID: 909ffacfb29f
Revises: 
Create Date: 2024-06-17 22:40:27.152600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909ffacfb29f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_nome'), 'categorias', ['nome'], unique=True)
    op.create_table('centros_treinamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('proprietario', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centros_treinamento_endereco'), 'centros_treinamento', ['endereco'], unique=True)
    op.create_index(op.f('ix_centros_treinamento_id'), 'centros_treinamento', ['id'], unique=False)
    op.create_index(op.f('ix_centros_treinamento_nome'), 'centros_treinamento', ['nome'], unique=True)
    op.create_index(op.f('ix_centros_treinamento_proprietario'), 'centros_treinamento', ['proprietario'], unique=False)
    op.create_table('atletas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('centro_treinamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['centro_treinamento_id'], ['centros_treinamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atletas_altura'), 'atletas', ['altura'], unique=False)
    op.create_index(op.f('ix_atletas_id'), 'atletas', ['id'], unique=False)
    op.create_index(op.f('ix_atletas_idade'), 'atletas', ['idade'], unique=False)
    op.create_index(op.f('ix_atletas_nome'), 'atletas', ['nome'], unique=True)
    op.create_index(op.f('ix_atletas_peso'), 'atletas', ['peso'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atletas_peso'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_nome'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_idade'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_id'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_altura'), table_name='atletas')
    op.drop_table('atletas')
    op.drop_index(op.f('ix_centros_treinamento_proprietario'), table_name='centros_treinamento')
    op.drop_index(op.f('ix_centros_treinamento_nome'), table_name='centros_treinamento')
    op.drop_index(op.f('ix_centros_treinamento_id'), table_name='centros_treinamento')
    op.drop_index(op.f('ix_centros_treinamento_endereco'), table_name='centros_treinamento')
    op.drop_table('centros_treinamento')
    op.drop_index(op.f('ix_categorias_nome'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
